### ISSUE TITLE
Add topic: puzzle-hunt

### ISSUE THREAD

**Issue by jenna-h** [obijywk/hunttracker#18]
Hello! Would you be open to adding the topic [puzzle-hunt](https://github.com/topics/puzzle-hunt) to this repository? I've been looking for puzzle hunt organization tools, and they're rather scattered right now. Cardinality's Small Board project uses this topic already, so I thought I'd ask the projects I've seen so far to start using it, too.

Thank you very much!

**Comment by obijywk** [comment]
Done - thanks for the suggestion! Added to https://github.com/obijywk/grilops as well.

**Comment by jenna-h** [comment]
I apologize for my fangirling, but someone sent me a link to Grilops last summer and I was nearly overcome by emotion: joy at the beautiful code, awe that someone would spend that kind of time working on a puzzle tool, and grief at my not having known about it sooner.

**Comment by obijywk** [comment]
Haha - thank you for the very kind feedback! It's exactly that kind of reaction that motivates me to spend the time working on it :smile:
